.TH "MASH BOUNDS" "1" "2018-07-09" "@VERSION@" "mash manual"
.SH NAME
mash paste \- Create a single sketch file from multiple sketch files
.SH SYNOPSIS
.B mash bounds
[\fIOPTIONS\fR...] \fIPREFIX\fR \fISKETCHES\fR...
.SH DESCRIPTION
.TP
Create a single sketch file from multiple sketch files.
.SH OPTIONS
.TP
\fB\-h\fR
Help
.TP
\fB\-l\fR
Input files are lists of file names.
.SH MASH
Part of the \fBmash\fR(1) program.
.SS
